FROM python:3.9-slim

RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN pip install --no-cache-dir prometheus-client

COPY fail2ban_config/exporter.py .

EXPOSE 9121
CMD ["python", "exporter.py"]