route:
  receiver: 'n8n-tickets'
  group_by: ['alertname', 'jail']
  group_wait: 30s 
  group_interval: 1m
  repeat_interval: 12h

   # Rutas específicas (Caida de servicios o ataque masivo no deben esperar 12 horas para repetir las alertas)
  routes:
    - match:
        alertname: Fail2banCaido
      repeat_interval: 15m 

    - match:
        alertname: AtaqueMasivo
      repeat_interval: 1h

receivers:
- name: 'n8n-tickets'
  webhook_configs:
  - url: 'http://n8n:5678/webhook/create-ticket'